version: 2
updates:
  # Go dependencies (weekly updates)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "private/harsh/sast-scan"
    open-pull-requests-limit: 5
    labels:
      - "security"
    reviewers:
      - "hsri-pf9"

  # GitHub Actions dependencies (weekly updates)
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    target-branch: "private/harsh/sast-scan"
    open-pull-requests-limit: 5
    labels:
      - "security"
    reviewers:
      - "hsri-pf9"
