run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gofmt
    - goimports
    - gci
    - unused
    - gosimple
    - unconvert
    - ineffassign
    - deadcode
    - structcheck
    - varcheck
    - asciicheck
    - depguard
    - gosec
    - typecheck   # ✅ Re-enable this

  disable:
    - lll
    - scopelint
    - interfacer
    - gochecknoglobals
    - gochecknoinits
    - nolintlint
    - funlen
    - testpackage
    - paralleltest

issues:
  max-issues-per-linter: 0
  exclude-use-default: false

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/clastix/cluster-api-control-plane-provider-kamaji)

  goheader:
    template: |
      Copyright 2023 Clastix Labs
      SPDX-License-Identifier: Apache-2.0
